name: Deploy to npm

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  # Build the frontend files
  build:
    name: Deploy changes to npm

    runs-on: ubuntu-latest

    steps:
      # Environment and dependency setup
      - name: Cloning repository
        uses: actions/checkout@v1

      # Set up node and install frontend dependencies
      - name: Set up Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: "Publish to NPM"
        run: |
          npm publish --access public
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
